### ISSUE TITLE
HttpUtility not available for .NET Framework on plugin version 8.4.0

### ISSUE THREAD

**Issue by yunxuchen** [AppLovin/AppLovin-MAX-Unity-Plugin#539]
### MAX Plugin Version

8.4.0

### Unity Version

6000.0.55f1

### Device/Platform Info

.NET Framework

### Current Behavior

Compilation fails when Api Compatibility Level in Project Settings is set to .Net Framework at this line:
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/679b17a19c0d9b3af7c1f99ff627e4022744645f/DemoApp/Assets/MaxSdk/Scripts/MaxWebRequest.cs#L275

Only happens for version 8.4.0, previous versions were working fine.

### Expected Behavior

Project compiles successfully in Unity projects using .NET Framework

### How to Reproduce

- Open Demo App.
- Switch Api Compatibility Level in Project Settings to .Net Framework.
- Project will get compilation error `Assets/MaxSdk/Scripts/MaxWebRequest.cs(275,25): error CS0103: The name 'HttpUtility' does not exist in the current context` 

### Reproducible in the demo app?

Yes

**Comment by JonathanLiuApp** [comment]
Hi @yunxuchen, we are aware of this issue and will have a fix for this in our next release. We will update here when the release is out.

**Comment by JonathanLiuApp** [comment]
[Max Unity Plugin 8.4.1](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_8_4_1) is out with a fix for this issue.
