### ISSUE TITLE
Build iOS failing with Facebook network v6.21.0.0 

### ISSUE THREAD

**Issue by Sonix9x** [AppLovin/AppLovin-MAX-Unity-Plugin#578]
### MAX Plugin Version

8.5.0

### Unity Version

6000.0.58f2

### Device/Platform Info

ios

### Current Behavior

ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked library 'libAppVerificationLibrary': library 'libAppVerificationLibrary' not found
ld: warning: Could not find or use auto-linked library 'swiftWebKit': library 'swiftWebKit' not found
ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation1': library 'swift_DarwinFoundation1' not found
ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation2': library 'swift_DarwinFoundation2' not found
ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation3': library 'swift_DarwinFoundation3' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'MACAVPlayer': framework 'MACAVPlayer' not found
ld: warning: Could not find or use auto-linked framework 'MACAdsQuality': framework 'MACAdsQuality' not found
ld: warning: Could not find or use auto-linked framework 'MACAnalytics': framework 'MACAnalytics' not found
ld: warning: Could not find or use auto-linked framework 'MACBase': framework 'MACBase' not found
ld: warning: Could not find or use auto-linked framework 'MACBaseUI': framework 'MACBaseUI' not found
ld: warning: Could not find or use auto-linked framework 'MACClientBidding': framework 'MACClientBidding' not found
ld: warning: Could not find or use auto-linked framework 'MACConsent': framework 'MACConsent' not found
ld: warning: Could not find or use auto-linked framework 'MACConsentManagement': framework 'MACConsentManagement' not found
ld: warning: Could not find or use auto-linked framework 'MACConstantsKit': framework 'MACConstantsKit' not found
ld: warning: Could not find or use auto-linked framework 'MACDebugPanel': framework 'MACDebugPanel' not found
ld: warning: Could not find or use auto-linked framework 'MACDependenciesUmbrella': framework 'MACDependenciesUmbrella' not found
ld: warning: Could not find or use auto-linked framework 'MACDivKit': framework 'MACDivKit' not found
ld: warning: Could not find or use auto-linked framework 'MACEncryption': framework 'MACEncryption' not found
ld: warning: Could not find or use auto-linked framework 'MACEventTracking': framework 'MACEventTracking' not found
ld: warning: Could not find or use auto-linked framework 'MACFalseClickKit': framework 'MACFalseClickKit' not found
ld: warning: Could not find or use auto-linked framework 'MACFeatureFlags': framework 'MACFeatureFlags' not found
ld: warning: Could not find or use auto-linked framework 'MACHeaderBidding': framework 'MACHeaderBidding' not found
ld: warning: Could not find or use auto-linked framework 'MACLogging': framework 'MACLogging' not found
ld: warning: Could not find or use auto-linked framework 'MACMediation': framework 'MACMediation' not found
ld: warning: Could not find or use auto-linked framework 'MACMraid': framework 'MACMraid' not found
ld: warning: Could not find or use auto-linked framework 'MACNative': framework 'MACNative' not found
ld: warning: Could not find or use auto-linked framework 'MACNetworking': framework 'MACNetworking' not found
ld: warning: Could not find or use auto-linked framework 'MACOpenMeasurement': framework 'MACOpenMeasurement' not found
ld: warning: Could not find or use auto-linked framework 'MACPlatformDescriptionKit': framework 'MACPlatformDescriptionKit' not found
ld: warning: Could not find or use auto-linked framework 'MACSDKConfigurationKit': framework 'MACSDKConfigurationKit' not found
ld: warning: Could not find or use auto-linked framework 'MACStoreKit': framework 'MACStoreKit' not found
ld: warning: Could not find or use auto-linked framework 'MACTimeTracking': framework 'MACTimeTracking' not found
ld: warning: Could not find or use auto-linked framework 'MACVASTKit': framework 'MACVASTKit' not found
ld: warning: Could not find or use auto-linked framework 'MobileAdsCore': framework 'MobileAdsCore' not found
ld: warning: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode16.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "_swift_coroFrameAlloc", referenced from:
      ___swift_coroFrameAllocStub in FBAudienceNetwork[18](FBANVideoViewSwift.o)
      ___swift_coroFrameAllocStub in FBAudienceNetwork[18](FBANVideoViewSwift.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### Expected Behavior

Build iOS

### How to Reproduce

Just build to iOS

### Reproducible in the demo app?

Not Tested

### Additional Info

Build with xcode 16.3
Building ok with Facebook network v.6.20.1.0
After update to 6.21.0.0 is failing

**Comment by Sonix9x** [comment]
UPD.
build with xcode 26.2
