### ISSUE TITLE
Unity Cloud Build iOS build failed with Amazon mediation: arm64 function not 4-byte aligned

### ISSUE THREAD

**Issue by pedro15** [AppLovin/AppLovin-MAX-Unity-Plugin#198]
### MAX Plugin Version

5.4.7

### Unity Version

2020.3.34f1

### Device/Platform Info

iOS

### Current Behavior

XCode compilation failed on Unity Cloud build using Amazon Mediation.

### Expected Behavior

XCode compilation successful on Unity Cloud build using Amazon Mediation.

### How to Reproduce

1. Download manually the amazon adapter from applovin website:
https://artifacts.applovin.com/unity/com/applovin/mediation/amazonadmarketplace-adapter/AppLovin-AmazonAdMarketplace-Adapters-Android-9.5.4.1-iOS-4.5.2.2.unitypackage

2. Import the package into the unity project

3. Fix the Dependencies.xml file (Assets/Maxsdk/Mediation/AmazonAdMarketplace/Dependencies.xml) with the existent libraries ( default xml configuration is wrong ):
```
<?xml version="1.0" encoding="utf-8"?>
<dependencies>
    <androidPackages>
        <androidPackage spec="com.applovin.mediation:amazon-publisher-services-adapter:9.5.7.0"/>
    </androidPackages>
	<iosPods>
        <iosPod name="AppLovinMediationAmazonAdMarketplaceAdapter" version="4.5.4.0" />
    </iosPods>
</dependencies>
```

4. save the project, upload to the repository and try to compile with unity cloud build using Xcode 13.3.1 or higher

### Additional Info

Unity Cloud build error log:

```
12332: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ▸ Linking UnityFramework
12333:  
12334: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ⚠;️  ld: arm64 function not 4-byte aligned: _unwind_tester from /BUILD_PATH/gamovation.chess-club.ios-dev/temp20220914-6488-12b8v9i/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
12335:  
12336: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ⚠;️  ld: Could not find or use auto-linked framework 'DTBiOSSDK'
12337:  
12338: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12339:  
12340: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ❌;  ld: symbol(s) not found for architecture arm64
12341:  
12342: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12343:  
12344: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12345:  
12346: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12347:  
12348: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
12349:  
12350: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12351:  
12352: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12353:  
12354: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: ** ARCHIVE FAILED **
12355:  
12356: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12357:  
12358: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 
12359:  
12360: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: The following build commands failed:
12361:  
12362: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: 	Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-frkydkzgcjghssapcukdzhkdhfzo/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
12363:  
12364: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: (1 failure)
12365:  
12366: [2022-09-14T21:21:33.137Z] - 6.4.1.2.4.2 - INFO: Exit status: 65
```

**Comment by santoshbagadi** [comment]
Hi @pedro15 , as mentioned in our [Preparing Mediation Networks guide](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters), the Amazon Publisher Services Integration Instructions are available here: https://dash.applovin.com/documentation/mediation/unity/mediation-adapters/amazon

Please let us know if you run into any other issues.
